#!/bin/bash
# -----------------------------------------------------------------------------
# AUTO-GENERATED DEPLOYMENT SCRIPT
# Generated by K8s Deployer UI
# -----------------------------------------------------------------------------

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# --- Configuration ---
REPO_URL=""
BRANCH="main"
NAMESPACE="app-deploy"
CLUSTER_NAME="kind"
PVC_SIZE="1Gi"
# Public Repository

# 1. Setup Environment
log_info "Initializing deployment for $REPO_URL on branch $BRANCH..."

IMAGE_TAG=$(shuf -i 10000-99999 -n 1)
log_info "Using Image Tag: $IMAGE_TAG"

CLONE_DIR="app-deploy-deploy"
MANIFESTS_DIR="$CLONE_DIR/manifests-k8s"

if [ -d "$CLONE_DIR" ]; then
    log_info "Cleaning up existing directory..."
    rm -rf "$CLONE_DIR"
fi

# 2. Clone Repository
log_info "Cloning repository..."
git clone --branch "$BRANCH" "$REPO_URL" "$CLONE_DIR"

cd "$CLONE_DIR"

# 3. Inject Environment Variables (Pre-configured via UI)
log_info "Injecting configured environment variables..."
# No custom environment variables configured

# 4. Cluster Setup

log_info "Using existing cluster: $CLUSTER_NAME"
if ! kind get clusters | grep -q "^$CLUSTER_NAME$"; then
    log_error "Cluster '$CLUSTER_NAME' not found! Please check your configuration."
    exit 1
fi


# 5. Build & Deploy Logic
# (This section reuses the robust logic from the original script but non-interactive)

log_info "Scanning for Dockerfiles..."
DOCKERFILES=$(find . -name "Dockerfile" -type f)

if [ -z "$DOCKERFILES" ]; then
    log_error "No Dockerfiles found."
    exit 1
fi

mkdir -p "$MANIFESTS_DIR"

# Create Namespace
cat > "$MANIFESTS_DIR/00-namespace.yaml" <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE
EOF

while read -r dockerfile; do
    DOCKERFILE_DIR=$(dirname "$dockerfile")
    
    if [ "$DOCKERFILE_DIR" = "." ]; then
        IMAGE_NAME="app:${IMAGE_TAG}"
        DEPLOYMENT_NAME="app"
    else
        SUBDIR=$(basename "$DOCKERFILE_DIR")
        IMAGE_NAME="app-$SUBDIR:${IMAGE_TAG}"
        DEPLOYMENT_NAME="app-$SUBDIR"
    fi
    
    log_info "Building $IMAGE_NAME..."
    docker build -t "$IMAGE_NAME" -f "$dockerfile" "$DOCKERFILE_DIR"
    
    log_info "Loading image into Kind..."
    kind load docker-image "$IMAGE_NAME" --name "$CLUSTER_NAME"

    # Minimal Deployment Generation
    cat > "$MANIFESTS_DIR/$DEPLOYMENT_NAME-deploy.yaml" <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT_NAME
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        app: $DEPLOYMENT_NAME
    spec:
      containers:
      - name: $DEPLOYMENT_NAME
        image: $IMAGE_NAME
        imagePullPolicy: IfNotPresent
EOF
done <<< "$DOCKERFILES"

# 6. Apply Manifests
log_info "Applying manifests to cluster..."
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
kubectl apply -f "$MANIFESTS_DIR/"

log_success "Deployment initiated! Check status with: kubectl get pods -n $NAMESPACE"
