import { DeploymentConfig, TaggingOption } from '../types';

export const generateBashScript = (config: DeploymentConfig): string => {
  const {
    repoUrl,
    isPublic,
    ghToken,
    branch,
    pvcSize,
    taggingOption,
    customTag,
    envVars,
    clusterName,
    createCluster,
    namespace
  } = config;

  // Helper to format env vars for the script injection
  const envVarBlock = envVars.map(ev => {
    if (ev.isSecret) {
      // Logic to inject simulated secret creation in the script
      return `echo "${ev.key}=${ev.value}" >> .env.secrets`;
    }
    return `echo "${ev.key}=${ev.value}" >> .env.config`;
  }).join('\n');

  const tagLogic = taggingOption === TaggingOption.RANDOM 
    ? 'IMAGE_TAG=$(shuf -i 10000-99999 -n 1)'
    : taggingOption === TaggingOption.TIMESTAMP
      ? 'IMAGE_TAG=$(date +%s)'
      : `IMAGE_TAG="${customTag}"`;

  const repoNameClean = repoUrl.split('/').pop()?.replace('.git', '') || 'app';
  const cleanNamespace = namespace || repoNameClean.toLowerCase().replace(/[^a-z0-9-]/g, '-');

  return `#!/bin/bash
# -----------------------------------------------------------------------------
# AUTO-GENERATED DEPLOYMENT SCRIPT
# Generated by K8s Deployer UI
# -----------------------------------------------------------------------------

set -euo pipefail

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
BLUE='\\033[0;34m'
NC='\\033[0m'

log_info() { echo -e "\${BLUE}[INFO]\${NC} \$1"; }
log_success() { echo -e "\${GREEN}[SUCCESS]\${NC} \$1"; }
log_error() { echo -e "\${RED}[ERROR]\${NC} \$1"; }

# --- Configuration ---
REPO_URL="${repoUrl}"
BRANCH="${branch}"
NAMESPACE="${cleanNamespace}"
CLUSTER_NAME="${clusterName}"
PVC_SIZE="${pvcSize}"
${!isPublic ? `GH_TOKEN="${ghToken}"` : '# Public Repository'}

# 1. Setup Environment
log_info "Initializing deployment for \$REPO_URL on branch \$BRANCH..."

${tagLogic}
log_info "Using Image Tag: \$IMAGE_TAG"

CLONE_DIR="${cleanNamespace}-deploy"
MANIFESTS_DIR="\$CLONE_DIR/manifests-k8s"

if [ -d "\$CLONE_DIR" ]; then
    log_info "Cleaning up existing directory..."
    rm -rf "\$CLONE_DIR"
fi

# 2. Clone Repository
log_info "Cloning repository..."
${!isPublic 
  ? `git clone --branch "\$BRANCH" "https://\${GH_TOKEN}@github.com/\${REPO_URL#https://github.com/}" "\$CLONE_DIR"` 
  : `git clone --branch "\$BRANCH" "\$REPO_URL" "\$CLONE_DIR"`
}

cd "\$CLONE_DIR"

# 3. Inject Environment Variables (Pre-configured via UI)
log_info "Injecting configured environment variables..."
${envVars.length > 0 ? envVarBlock : '# No custom environment variables configured'}

# 4. Cluster Setup
${createCluster ? `
log_info "Ensuring Kind cluster '\$CLUSTER_NAME' exists..."
if ! kind get clusters | grep -q "^\$CLUSTER_NAME\$"; then
    kind create cluster --name "\$CLUSTER_NAME"
else
    log_info "Cluster '\$CLUSTER_NAME' already exists."
fi
` : `
log_info "Using existing cluster: \$CLUSTER_NAME"
if ! kind get clusters | grep -q "^\$CLUSTER_NAME\$"; then
    log_error "Cluster '\$CLUSTER_NAME' not found! Please check your configuration."
    exit 1
fi
`}

# 5. Build & Deploy Logic
# (This section reuses the robust logic from the original script but non-interactive)

log_info "Scanning for Dockerfiles..."
DOCKERFILES=$(find . -name "Dockerfile" -type f)

if [ -z "\$DOCKERFILES" ]; then
    log_error "No Dockerfiles found."
    exit 1
fi

mkdir -p "\$MANIFESTS_DIR"

# Create Namespace
cat > "\$MANIFESTS_DIR/00-namespace.yaml" <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: \$NAMESPACE
EOF

while read -r dockerfile; do
    DOCKERFILE_DIR=$(dirname "\$dockerfile")
    
    if [ "\$DOCKERFILE_DIR" = "." ]; then
        IMAGE_NAME="${repoNameClean}:\${IMAGE_TAG}"
        DEPLOYMENT_NAME="${repoNameClean}"
    else
        SUBDIR=$(basename "\$DOCKERFILE_DIR")
        IMAGE_NAME="${repoNameClean}-\$SUBDIR:\${IMAGE_TAG}"
        DEPLOYMENT_NAME="${repoNameClean}-\$SUBDIR"
    fi
    
    log_info "Building \$IMAGE_NAME..."
    docker build -t "\$IMAGE_NAME" -f "\$dockerfile" "\$DOCKERFILE_DIR"
    
    log_info "Loading image into Kind..."
    kind load docker-image "\$IMAGE_NAME" --name "\$CLUSTER_NAME"

    # Minimal Deployment Generation
    cat > "\$MANIFESTS_DIR/\$DEPLOYMENT_NAME-deploy.yaml" <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: \$DEPLOYMENT_NAME
  namespace: \$NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: \$DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        app: \$DEPLOYMENT_NAME
    spec:
      containers:
      - name: \$DEPLOYMENT_NAME
        image: \$IMAGE_NAME
        imagePullPolicy: IfNotPresent
EOF
done <<< "\$DOCKERFILES"

# 6. Apply Manifests
log_info "Applying manifests to cluster..."
kubectl create namespace "\$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
kubectl apply -f "\$MANIFESTS_DIR/"

log_success "Deployment initiated! Check status with: kubectl get pods -n \$NAMESPACE"
`;
};